# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!

target 'MAGWebViewPlugin' do

  pod 'Masonry', '1.1.0'
  pod 'MJRefresh', '3.1.16'
  pod 'WebViewJavascriptBridge', '~> 6.0'
  
end
